---
name: dcegm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pytest
  - pytest-cov
  - pytest-xdist

  # Package dependencies
  - numpy
  - scipy
  - numba
  - pandas
  - jax
  - matplotlib
  - statsmodels.api
  - os

  # Misc
  - black
  - nb_black
  - flake8
  - jupyterlab
  - matplotlib
  - pdbpp
  - pre-commit
  - setuptools_scm
  - toml

  # Conda
  - anaconda-client
  - conda-build
  - conda-verify
  - tox-conda
  - pip:
      - blackcellmagic
      - furo

      # Development dependencies
      - git+https://github.com/OpenSourceEconomics/upper-envelope.git
      - git+https://github.com/OpenSourceEconomics/dcegm.git@ce19ebbd8eb9b713a7a256b8310ed1bac9351b36#egg=dcegm
